---
version: 2.1

orbs:
  terraform: twdps/terraform@dev:<<pipeline.git.revision>>
  # orb-tools: circleci/orb-tools@12.0.4

globals:
  - &context orb-publishing
  - &orb-name twdps/terraform

# commands:
#   assert-generated-file-against-expected:
#     parameters:
#       generated-file:
#         type: string
#     steps:
#       - run:
#           name: test sbxdev template file against expected
#           command: |
#             export result=$(cmp -s chart/overlays/compare-sbxdev.yaml << parameters.generated-file >>; echo $?)
#             if [[ $result -ne 0 ]]; then
#               echo "error: sbxdev-sample-app.yaml does not match expected output"
#               exit 1
#             fi

jobs:

  test packages command:
    docker:
      - image: twdps/circleci-infra-aws:alpine-stable
    steps:
      - checkout
      - terraform/packages:
          terraform-version: 1.6.0
          tflint-version: 0.48.0
          tfsec-version: 1.28.4
          trivy-version: 0.46.0
          checkov-version: 2.5.13
          snyk-version: 1.1236.0

workflows:
  version: 2

  integration tests:
    jobs:
      - test packages command