---
version: 2.1

orbs:
  terraform: twdps/terraform@dev:<<pipeline.git.revision>>
  # orb-tools: circleci/orb-tools@12.0.4

globals:
  - &context orb-publishing
  - &orb-name twdps/terraform

commands:

  before-job-message:
    parameters:
      msg:
        type: string
    steps:
      - run:
          name: echo before-msg
          command: echo "before - << parameters.msg >>"

  after-job-message:
    parameters:
      msg:
        type: string
    steps:
      - run:
          name: echo after-msg param
          command: echo "after - << parameters.msg >>"
jobs:

  test packages command:
    docker:
      - image: twdps/circleci-infra-aws:alpine-stable
    steps:
      - checkout
      - terraform/packages:
          terraform-version: 1.6.0
          tflint-version: 0.48.0
          tfsec-version: 1.28.4
          trivy-version: 0.46.0
          checkov-version: 2.5.13
          snyk-version: 1.1236.0
          terrascan-version: 1.18.3
          driftctl-version: 0.39.0
          infracost-version: 0.10.29

workflows:
  version: 2

  integration tests:
    jobs:
      #- test packages command

      - terraform/static-analysis:
          working-directory: test
          # terraform-init-additional-args:
          # terraform-validate:
          # terraform-version:
          # tflint-version:
          # tflint-provider:
          # tflint-additional-args:
          # tfsec-version:
          # tfsec-additional-args:
          # snyk-version:
          # snyk-token:
          # snyk-organization:
          # snyk-additional-args:
          # trivy-version:
          # checkov-version:
          # checkov-additional-args:
          # terrascan-version:
          # terrascan-init-args:
          # terrascan-iac-type:
          # terrascan-policy-type:
          # terrascan-custom-scan-args:
          # driftctl-version:
          # driftctl-additional-args:
          # infracost-version:
          # infracost-api-key:
          # infracost-additional-args:
          before-static-analysis:
            - before-job-message:
                msg: Hello, before!
          after-static-analysis:
            - after-job-message:
                msg: Hello, after!