---
version: 2.1

orbs:
  terraform: twdps/terraform@dev:<<pipeline.git.revision>>
  # orb-tools: circleci/orb-tools@12.0.4

globals:
  - &context orb-publishing
  - &orb-name twdps/terraform
  - &shell op run --env-file op.env -- /bin/bash -eo pipefail

commands:

  before-job-message:
    parameters:
      msg:
        type: string
    steps:
      - run:
          name: echo before-msg
          command: echo "before - << parameters.msg >>"

  after-job-message:
    parameters:
      msg:
        type: string
    steps:
      - run:
          name: echo after-msg param
          command: echo "after - << parameters.msg >>"

  add-for-plan-test:
    steps:
      - run:
          name: reconfigure versions.tf fixture for plan test
          command: |
          
jobs:

  test packages command:
    docker:
      - image: twdps/circleci-infra-aws:alpine-stable
    steps:
      - checkout
      - terraform/packages:
          terraform-version: 1.6.0
          tflint-version: 0.48.0
          tfsec-version: 1.28.4
          trivy-version: 0.46.0
          checkov-version: 2.5.13
          snyk-version: 1.1236.0
          terrascan-version: 1.18.3
          driftctl-version: 0.39.0
          infracost-version: 0.10.29

workflows:
  version: 2

  integration tests:
    jobs:
      #- test packages command

      - terraform/static-analysis:
          context: *context
          shell: *shell
          working-directory: test
          tflint-version: installed
          tflint-provider: aws
          tflint-additional-args: --format=compact --force
          tfsec-version: installed
          tfsec-additional-args: --exclude aws-ec2-no-excessive-port-access,aws-ec2-no-public-ingress-acl,aws-ec2-require-vpc-flow-logs-for-all-vpcs
          trivy-version: installed
          trivy-commandline-args: config . --exit-code 0
          snyk-version: installed
          snyk-organization: twdps
          snyk-additional-args: --report --target-name=orb-terraform-ci
          checkov-version: installed
          checkov-additional-args: -d . --skip-check CKV_TF_1 
          terrascan-version: installed
          terrascan-custom-scan-args: -t aws -i terraform --output=yaml -d test/ --skip-rules="AC_AWS_0369"
          driftctl-version: installed
          driftctl-additional-args: --help
          infracost-version: installed
          infracost-additional-args: breakdown --path .
          before-static-analysis:
            - terraform/packages:
                terrascan-version: 1.18.3
                infracost-version: 0.10.29
                trivy-version: 0.46.0
            - before-job-message:
                msg: Hello, before!
          after-static-analysis:
            - after-job-message:
                msg: Hello, after!

      # - terraform/plan:
      #     context: *context
      #     shell: *shell
      #     working-directory: test
      #     workspace: orb-terraform
      #     terraform-var-file: varfile-check.tfvars
      #     terraform-plan-outfile: filename-check.json
      #     snyk-version: installed
      #     snyk-organization: twdps
      #     checkov-version: installed
      #     trivy-version: installed
      #     tfc-workspace: orb-terraform-test
      #     tfc-organization: twdps
      #     before-terraform:
      #       - add-for-plan-test
      #       - before-job-message:
      #           msg: Hello, before!
      #     after-terraform-init:
      #       - after-job-message:
      #           msg: Hello, after init!
      #     after-terraform:
      #       - after-job-message:
      #           msg: Hello, after!